ChileCompraExpress.Web/ViewModels/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChileCompraExpress.Web.ViewModels
{
    public class Producto
    {
        public int Id { get;  set; }        
        public double PrecioAnterior { get;  set; }
        public double Precio { get;  set; }

        private string filtroGrl;

        public string FiltroGrl
        {
            get { return filtroGrl; }
            set { filtroGrl = value; }
        }       


        private string nombre;

        public string Nombre
        {
            get { return nombre; }
            set { nombre = value; }
        }
        

        private string marca;

        public string Marca
        {
            get { return marca; }
            set { marca = value; }
        }

        private int idRegion;

        public int IdRegion
        {
            get { return idRegion; }
            set { idRegion = value; }
        }

        private string region;

        public string Region
        {
            get { return region; }
            set { region = value; }
        }

        private int idRango;

        public int IdRango
        {
            get { return idRango; }
            set { idRango = value; }
        }

        private string rango;

        public string Rango
        {
            get { return rango; }
            set { rango = value; }
        }

        private int idProveedor;

        public int IdProveedor
        {
            get { return idProveedor; }
            set { idProveedor = value; }
        }

        private string proveedor;

        public string Proveedor
        {
            get { return proveedor; }
            set { proveedor = value; }
        }
        
        
        private int idConvenio;

        public int IdConvenio
        {
            get { return idConvenio; }
            set { idConvenio = value; }
        }

        private string convenio;

        public string Convenio
        {
            get { return convenio; }
            set { convenio = value; }
        }
        
        

        public int Descuento
        {
            get
            {
                if (PrecioAnterior == 0) return 0;

                int intref = (int)(((PrecioAnterior - Precio) / PrecioAnterior) * 100);
                return intref / 5 * 5;
            }
        }

        public string UrlImagen
        {
            get
            {
               return "Content/images/products/producto_test.jpg";
            }
        }

        public static Producto Muestra()
        {
            return new Producto
            {
                Id = 235623,
                Nombre = "Catridge Negro Laser",
                Proveedor = "Transportes Arauco",
                PrecioAnterior = 160000,
                Precio = 120000,
            };
        }

        public static IEnumerable<Producto> Flujo()
        {
            return new Producto[] { 
                new Producto{ 
                    Id=235623,
                    Nombre = "Catridge Negro Laser",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 130000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Yogurt Surlat",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 140000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Mortadela Lisa",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 110000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Jamón Ahumado Cerdo",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 100000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Ibuprofeno 800mg",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio =80000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Jabón Palmolive",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 90000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Neumáticos",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 110000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Lubricante de autos",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 100000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Colector de vapores",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 110000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Queso Mozarella",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 120000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Atún enlatado",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 110000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Galletas de sal",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 90000,
                },
                new Producto{ 
                    Id=235623,
                    Nombre = "Salsa de soja",
                    Proveedor = "Transportes Arauco",
                    PrecioAnterior = 160000,
                    Precio = 50000,
                }
            };
        }
    }
}

ChileCompraExpress.Web/Controllers/EscritorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChileCompraExpress.Web.ViewModels;

namespace ChileCompraExpress.Web.Controllers
{
    public class EscritorioController :Controller//: BaseController
    {
        //
        // GET: /Escritorio/

        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch(Exception ex)
            {
                throw (ex);
            }

        }

        public PartialViewResult Loading()
        {
            try
            {
                return PartialView("~/Views/Escritorio/Loader.cshtml");
            }
            catch (Exception ex)
            {
                throw (ex);
            }

        }

        public void SetSessionItems(string count)
        {
            Helpers.SessionHelper sesionCountItem = new Helpers.SessionHelper();
            sesionCountItem.SetCountItems(count);
        }
    }
}

ChileCompraExpress.Web/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using ChileCompraExpress.Web.ViewModels;
using ChileCompraExpress.XmlParserLibrary.Models;
using ChileCompraExpress.XmlParserLibrary;
using System.Text.RegularExpressions;
using ChileCompraExpress.Web.Models;
using System.Diagnostics;
using ChileCompraExpress.Business;
using ChileCompraExpress.Utilities;
using System.IO;
using System.Text;
using System.Web.Script.Serialization;
using System.Configuration;


namespace ChileCompraExpress.Web.Controllers
{
    public class ProductosController : Controller
    {


  

        [HttpPost]
        public string GetBaseProducto(Entities.Producto prd)
        {
            ProductoBsn prdBsn = new ProductoBsn();
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Entities.Producto producto = prdBsn.GetBaseProducto(prd);
            return serializer.Serialize(producto);
        }

        [HttpPost]
        public string VerFicha(Entities.Producto prd)
        {
            ProductoBsn prdBsn = new ProductoBsn();
            Helpers.SessionHelper sessionHelper = new Helpers.SessionHelper();
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            ChileCompraExpress.Entities.Usuario user = sessionHelper.GetUser();
            prd.IdUser = user.Code;
            

            Entities.Producto producto = prdBsn.InsertarHit(prd);
            producto.IdUser = user.Code;
            producto.CodeUsrOrg = user.Code + "_" + user.Organization.Code;

            return serializer.Serialize(producto);
        }

        private List<KeyValuePair<string, string>> splitParams(string q)
        {
            var result = new List<KeyValuePair<string, string>>();

            q = q.Replace("+", "++") + "+";
            var param = new Regex(@"\+inmeta:(?<name>.*?)(%3D|:)(?<value>.*?)\+");

            foreach (Match p in param.Matches(q))
            {
                result.Add(new KeyValuePair<string, string>(p.Groups["name"].Value, p.Groups["value"].Value.Replace("%2520", "%20").Replace("%20", "").Replace("%252E", ".").Replace("%252D", "-")
                    .Replace("%C3%A1", "á").Replace("%C3%A9", "é").Replace("%C3%AD", "í").Replace("%C3%B3", "ó").Replace("%C3%BA", "ú")
                    .Replace("%C3%81", "Á").Replace("%C3%89", "É").Replace("%C3%8D", "Í").Replace("%C3%93", "Ó").Replace("%C3%9A", "Ú")
                    .Replace("%2F", "/")
                    .Replace("%2524","$")
                    ));
            }
            return result;
        }

        private List<KeyValuePair<string, string>> splitParamsRequiredFields(string q,string required)
        {
            var result = new List<KeyValuePair<string, string>>();

            //q = q.Replace("+", "++") + "+";
            var param = new Regex(@"\((?>[^()]+|    \( (?<number>)|    \) (?<-number>))*(?(number)(?!))\)");

            foreach (Match p in param.Matches(required))
            {                
                string[] splitDot = p.Value.Split(':');
                splitDot[0] = splitDot[0].Replace("(", "");
                splitDot[1] = splitDot[1].Replace(")", "").ToString();
                result.Add(new KeyValuePair<string, string>(splitDot[0], splitDot[1].Replace("%2520", "%20").Replace("%20", "").Replace("%252E", ".").Replace("%252D", "-")
                    .Replace("%C3%A1", "á").Replace("%C3%A9", "é").Replace("%C3%AD", "í").Replace("%C3%B3", "ó").Replace("%C3%BA", "ú")
                    .Replace("%C3%81", "Á").Replace("%C3%89", "É").Replace("%C3%8D", "Í").Replace("%C3%93", "Ó").Replace("%C3%9A", "Ú")
                    .Replace("%2F", "/")
                    .Replace("%24", "$")));
            }

            q = q.Replace("+", "++") + "+";
            q = "+" + q;
            var paramInmeta = new Regex(@"\+inmeta:(?<name>.*?)(%3D|:)(?<value>.*?)\+");

            foreach (Match p in paramInmeta.Matches(q))
            {
                result.Add(new KeyValuePair<string, string>(p.Groups["name"].Value, p.Groups["value"].Value.Replace("%2520", "%20").Replace("%20", "").Replace("%252E", ".").Replace("%252D", "-")
                    .Replace("%C3%A1", "á").Replace("%C3%A9", "é").Replace("%C3%AD", "í").Replace("%C3%B3", "ó").Replace("%C3%BA", "ú")
                    .Replace("%C3%81", "Á").Replace("%C3%89", "É").Replace("%C3%8D", "Í").Replace("%C3%93", "Ó").Replace("%C3%9A", "Ú")
                    .Replace("%2F", "/")));
            }

            return result;
        }

        [ActionName("Index"), HttpGet]
        public ActionResult Index()
        {
            return Index(" ");
        }

        [HttpPost]
        public PartialViewResult GetMasProveedores(Producto prod)
        {
            ProveedorBsn proveedorBsn = new ProveedorBsn();
            //Helpers.SessionHelper sessionHelper = new Helpers.SessionHelper();
            //ChileCompraExpress.Entities.Usuario user = sessionHelper.GetUser();
            string session = Session.SessionID;

            Entities.Proveedor[] proveedor = proveedorBsn.proveedores(prod.Id, prod.IdConvenio, session);
            return PartialView("~/Views/Productos/Buscar/ResponseMasProveedores.cshtml", proveedor);
        }

        [HttpPost]
        public ActionResult GetProveedores(string text)
        {
            
            ProveedorBsn proveedorBsn = new ProveedorBsn();
            Entities.Proveedor[] provs = proveedorBsn.proveedoresByText(text);

            var proveedors = new List<KeyValuePair<string, string>>();
            if (provs != null && provs.Length > 0)
            {
                for (int i = 0; i < provs.Length; i++)
                {
                    proveedors.Add(new KeyValuePair<string, string>(provs.ElementAt(i).Id.ToString(), provs.ElementAt(i).Nombre.ToString()));
                }
            }
    
            
            var result = proveedors.Where(r => r.Value.ToLower().Contains(text.ToLower()))
                        .Select(r => new { id = r.Key, label = r.Value, name = r.Value });

          
            return Json(result);
        }

        
        [ActionName("Index"), HttpPost]
         public ActionResult Index(string q, int startsFrom = 0, int itemsPerPage = 10, string sortBy = "", string sortReverse = "false", string esMasVisto = "false",int ClickedItem=0,string input = "")
        {
            
            sortReverse = (sortReverse == null || sortReverse == "") ? "false" : sortReverse;
            bool sortRev = Convert.ToBoolean(sortReverse);
            if (!string.IsNullOrWhiteSpace(q) && (!bool.Parse(esMasVisto)))
            {
                string url = @"" + ConfigurationSettings.AppSettings["IP_GSA"] + "/search?client=publico&getfields=*&getfields=*&site=publico&filter=0&lr=lang_es&proxyreload=1&q=" + q;

                ViewBag.SliderReset = true;
                if (url.Contains(".."))
                {
                    ViewBag.SliderReset = false;
                }
                ParmModel PARMObject;
                List<RModel> RList;
                List<SearchParamModel> searchParams;

                var xmlParser = new XmlParser();
                var result = xmlParser.ParsebyUrl(url, sortBy, sortRev, ClickedItem, itemsPerPage, out PARMObject, out RList, out searchParams);
                ViewBag.itemsTotalCount = result.count;
                ViewBag.itemsCount = RList.Count;
                ViewBag.suggestionHtml = result.suggestionHtml;
                ViewBag.input = result.suggestionHtml;

                ViewBag.ClickedItem = ClickedItem;
                if (result.count < startsFrom)
                {
                    startsFrom = 0;
                }
                ViewBag.itemsStarts = startsFrom;
                ViewBag.Num = itemsPerPage;

                ViewBag.Products = RList;
                ViewBag.PARM = PARMObject;
                ViewBag.SearchParams = searchParams;

                //int minPrice = result.minPrice;
                //int maxPrice = result.maxPrice;

                var qParams = searchParams.Where(x => x.name == "q").SingleOrDefault();

                string SplitItem = qParams.original_value;
                string[] SplitItems = SplitItem.Split('+');

                string VItemName = SplitItems[0];
                List<KeyValuePair<string, string>> qParamsList = null;
                if (qParams != null)
                {
                    qParamsList = splitParams(qParams.original_value);
                }
                ViewBag.qParams = qParamsList;

                string urlItem = @"" + ConfigurationSettings.AppSettings["IP_GSA"] + "/search?btnG=Google+Search&client=publico&sort=date%3AD%3AL%3Ad1&oe=UTF-8&ie=UTF-8&ud=1&getfields=*&getfields=*&exclude_apps=1&site=publico&filter=0&lr=lang_es&proxyreload=1&q=" + VItemName;
                ParmModel PARMObjectItem;
                List<RModel> RListItem;
                List<SearchParamModel> searchParamsItem;

                var xmlParserItem = new XmlParser();
                var resultItem = xmlParser.ParsebyUrl(urlItem, sortBy, sortRev, startsFrom, itemsPerPage, out PARMObjectItem, out RListItem, out searchParamsItem);

                int minPrice = resultItem.minPrice;
                int maxPrice = resultItem.maxPrice;

                string min_value = minPrice.ToString();
                string max_value = maxPrice.ToString();
                if ((qParamsList as List<KeyValuePair<string, string>>).Where(x => x.Key == "PM").Count() > 0)
                {
                    string range = (qParamsList as List<KeyValuePair<string, string>>).Where(x => x.Key == "PM").First().Value;
                    min_value = range.Split('.')[0];

ChileCompraExpress.Web/Views/Productos/Index.cshtml
@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_Layout.cshtml";
}

@model  ChileCompraExpress.Web.ViewModels.Producto

@{
    ViewBag.Title = "Productos";
}
@section scripts {

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   
}
<div id="contenido" class="centro">
    @{
        Html.RenderPartial("Filtros/FiltrosIzq");
    }
    <div id="bloq_centro_2">
            @{
        //FILTROS DE RESULTADOS DE BUSQUEDA
            }
            <div id="resultados_filtros">
                <a class="azulink subr" href="@Url.Action("Index", "Escritorio")">Página Principal</a> <label> >> Página de resultados </label><br /><br />
                <label id="Label1" class="chico">
                @if(!String.IsNullOrEmpty(ViewBag.suggestionHtml))
                {
                    @:Quizás quiso decir</label> 
                }               
                <a href="#" class="subr azul" onclick="quizoDecir('@(ViewBag.suggestionHtml as string)');">
                    @(ViewBag.suggestionHtml as string)
                </a>
            </div>
            <div class="resultados_filtros_1">
                <label id="Label3" class="grande negrita gris_3">
                    Los resultados para</label>
                <label id="lbl_resultado_para" class="grande negrita gris_3">                
                </label><br /><br />
                <div class="resultados_filtros_1_1">
                    <label id="Label16" class="mediano gris_2">
                    @{
                        int itemStarts = (ViewBag.itemsStarts == null) ? 0 : (ViewBag.itemsStarts as int?).Value;
                        int itemClicked = (ViewBag.ClickedItem == null) ? 0 : (ViewBag.ClickedItem as int?).Value;
                        int itemsCount = (ViewBag.itemsCount == null) ? 0 : (ViewBag.itemsCount as int?).Value;
                        int itemsTotalCount = (ViewBag.itemsTotalCount == null) ? 0 : (ViewBag.itemsTotalCount as int?).Value;
                    }
                    @if (itemsCount > 0)
                    {
                       <span>@(itemClicked + 1) al @(itemClicked + itemsCount) de</span> 
                    } 
                    @itemsTotalCount encontrados</label>
                        <input type="hidden" id="elementsTotalCount" name="elementsTotalCount" value="@(ViewBag.itemsTotalCount as int?)" />
                        <input type="hidden" id="elementsStarts" name="elementsStarts" value="@(ViewBag.itemsStarts as int?)" />
                        <input type="hidden" id="elementsClicked" name="elementsClicked" value="@(ViewBag.ClickedItem as int?)" />
                        <input type="hidden" id="elementsCount" name="elementsCount" value="@(ViewBag.itemsCount as int?)" />
                        <input type="hidden" id="sortBy" name="sortBy" value="@(ViewBag.sortBy as string)" />
                        <input type="hidden" id="sortReverse" name="sortReverse" value="@(ViewBag.sortReverse as string)" />
                        <input type="hidden" id="num" name="num" value="@(ViewBag.Num as int?)" />
                        <input type="hidden" id="esMasVisitado" value="false" />
                </div>
                     
                 @{ Html.RenderPartial("Filtros/FiltrosPaginacion"); }
                
            </div>
                        
            <div id="bloq_resultados" > 
                 @{ Html.RenderPartial("Buscar/ResponseProductos"); }
            </div>
            <br />
            <div class="resultados_filtros_1">
                @{ Html.RenderPartial("Filtros/FiltrosPaginacion"); }
           </div>
           <br /><br /><br />
     </div>

    <script type="text/javascript">

        $(document).ready(function () {
            $('.btn_masproveedores_1').click(function () {
                $(this).toggleClass('opened');

                var moreBlock = $(this).parent().find('.div_mas_proveedores')

                if ($(this).hasClass('opened')) {
                    $(moreBlock).show();
                    $(this).find('.btn_mas_proveedores_2.moreClosed').hide();
                    $(this).find('.btn_mas_proveedores_2.moreOpen').show();
                }
                else {
                    $(moreBlock).hide();
                    $(this).find('.btn_mas_proveedores_2.moreClosed').show();
                    $(this).find('.btn_mas_proveedores_2.moreOpen').hide();
                }
            });

            if (esMasVisitado) {

                $("#lbl_resultado_para").text("los más visitados");
            }
            else {

                $("#lbl_resultado_para").text($("#q").val());

            }
        });

    </script>
 </div>
 

            